[package]
name = "variants_actix_web"
version = "0.1.0"
edition = "2024"
workspace = "../../../"

[dependencies]
actix-web = "4.11.0"
normpath = "1.3.0"
variants = { version = "0.1.0", path = "../../lib" }
variants_codegen = { version = "0.1.0", path = "../codegen" }

[lints]
workspace = true
