name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build core
      run: cargo build --verbose
      working-directory: ./rust
    - name: Run core tests
      run: cargo test --verbose
      working-directory: ./rust
    - name: Build examples
      run: cargo build --verbose
      working-directory: ./rust/examples
