name: Varaints_CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.platforms.distro }}
    strategy: 
      matrix:
        platforms:
          - { name: macOS, distro: macOS-latest, toolchain: stable }
          - { name: Linux, distro: ubuntu-latest, toolchain: stable }
          - { name: Windows, distro: windows-latest, toolchain: stable }

    steps:
    - name: Checkout 
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.platforms.toolchain }}

    - name: Build core
      run: cargo build --verbose
      working-directory: ./rust
      
    - name: Run core tests
      run: cargo test --verbose
      working-directory: ./rust
      
    - name: Build examples
      run: cargo build --verbose
      working-directory: ./rust/examples
